---
# Adding lo0 interface configuration outside of apply-groups fpr Contrail Command 5.0.1-0.214 
  - name: Create config snippet directory for device
    file: path=configs/snippets/{{ inventory_hostname }} state=directory
    tags: common

  - name: Build config and puting it into -snippets- directory
    template: src=contrail-command-fix.j2 dest=configs/snippets/{{ inventory_hostname }}/contrail-command-fix.conf
    tags: common

