host_name: qfx5200-r01-01 
management_interface_ip: 172.30.104.149/23
lo0_ip: 10.255.253.149

inet_interfaces:
  - name: et-0/0/30
    ip_address: 10.255.3.13/31
    description: to qfx10002-r01-03
  - name: et-0/0/31
    ip_address: 10.255.3.15/31
    description: to qfx10002-r01-04

underlay_inet_interfaces:
  - et-0/0/30
  - et-0/0/31

#ae_interfaces:
#  - name: ae0
#    description: my interface
#    esi: 00:00:11:11:22:22:33:33:44:44
#    mode: all-active
#    ae_members:
#      - ge-0/0/0
#      - ge-0/0/1
#  - name: ae1
#    description: your interface
#    esi: 00:00:11:11:22:22:33:33:44:45
#    mode: all-active
#    ae_members:
#      - ge-0/0/2
#      - ge-0/0/3
